services:
  app:
    image: fatimaazam/personal-notes-app:latest
    container_name: notes_app_ci
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: notes_mongo_ci
    volumes:
      - mongo_data_ci:/data/db
    restart: unless-stopped

volumes:
  mongo_data_ci: