pipeline {
    agent any

    environment {
        COMMIT_AUTHOR_EMAIL = ''
        FALLBACK_EMAIL = 'fatimaazam2111@gmail.com'
    }

    stages {
        stage('Get Commit Author Email') {
            steps {
                script {
                    def email = sh(
                        script: "git show -s --format='%ae' HEAD || true",
                        returnStdout: true
                    ).trim()

                    if (!email || email == 'null' || email == 'null@gmail.com' || email.contains('users.noreply.github.com')) {
                        email = env.FALLBACK_EMAIL
                    }

                    env.COMMIT_AUTHOR_EMAIL = email
                    echo "Email will be sent to: ${env.COMMIT_AUTHOR_EMAIL}"
                }
            }
        }

        stage('Create Env') {
            steps {
                sh '''
                cat > .env <<EOF
MONGO_URI=mongodb://mongo:27017/personal_notes_db
JWT_SECRET=myverysecretkey
PORT=5000
EOF
                '''
            }
        }

        stage('Stop Old Deployment') {
            steps {
                sh 'docker compose -f docker-compose.jenkins.yml down || true'
            }
        }

        stage('Start Deployment') {
            steps {
                sh 'docker compose -f docker-compose.jenkins.yml up -d'
            }
        }

        stage('Show Containers') {
            steps {
                sh 'docker ps'
            }
        }

        stage('Wait for App') {
            steps {
                sh '''
                MAX=30
                i=0

                while [ $i -lt $MAX ]; do
                  if curl -sSf --max-time 5 http://localhost:5001 > /dev/null 2>&1; then
                    echo "App is reachable at http://localhost:5001"
                    exit 0
                  fi

                  i=$((i+1))
                  echo "Waiting for app... attempt $i/$MAX"
                  sleep 2
                done

                echo "App did not respond after $MAX attempts"
                echo "===== Running containers ====="
                docker ps
                echo "===== App logs ====="
                docker logs notes_app_ci || true
                echo "===== Mongo logs ====="
                docker logs notes_mongo_ci || true
                exit 1
                '''
            }
        }

        stage('Run Selenium Tests in Docker') {
            steps {
                sh '''
                docker run --rm --network host \
                  -e APP_URL=http://localhost:5001 \
                  -v "$PWD/selenium-tests":/workspace \
                  -w /workspace \
                  markhobson/maven-chrome mvn test
                '''
            }
        }
    }

    post {
        always {
            script {
                def recipient = env.COMMIT_AUTHOR_EMAIL?.trim()

                if (!recipient || recipient == 'null' || recipient == 'null@gmail.com' || recipient.contains('users.noreply.github.com')) {
                    recipient = env.FALLBACK_EMAIL
                }

                echo "Final email recipient: ${recipient}"

                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    emailext(
                        subject: "${JOB_NAME} - Build #${BUILD_NUMBER} - ${currentBuild.currentResult}",
                        body: """
Build Result: ${currentBuild.currentResult}
Build URL: ${env.BUILD_URL}

Test results were generated by Jenkins pipeline.
""",
                        to: recipient
                    )
                }
            }
        }
    }
}