pipeline {
    agent any

    environment {
        COMMIT_AUTHOR_EMAIL = ''
    }

    stages {
        stage('Create Env') {
            steps {
                sh '''
                cat > .env <<EOF
MONGO_URI=mongodb://mongo:27017/personal_notes_db
JWT_SECRET=myverysecretkey
PORT=5000
EOF
                '''
            }
        }

        stage('Stop Old Deployment') {
            steps {
                sh 'docker compose -f docker-compose.jenkins.yml down || true'
            }
        }

        stage('Start Deployment') {
            steps {
                sh 'docker compose -f docker-compose.jenkins.yml up -d'
            }
        }

        stage('Show Containers') {
            steps {
                sh 'docker ps'
            }
        }

        stage('Get Commit Author Email') {
            steps {
                script {
                    env.COMMIT_AUTHOR_EMAIL = sh(
                        script: "git log -1 --pretty=format:'%ae'",
                        returnStdout: true
                    ).trim()

                    if (!env.COMMIT_AUTHOR_EMAIL) {
                        env.COMMIT_AUTHOR_EMAIL = 'fatimaazam2111@gmail.com'
                    }

                    echo "Email will be sent to: ${env.COMMIT_AUTHOR_EMAIL}"
                }
            }
        }

        stage('Wait for App') {
            steps {
                sh '''
                # App container internal port is 5000, but host port is 5001
                MAX=30
                i=0

                while [ $i -lt $MAX ]; do
                  if curl -sSf --max-time 5 http://localhost:5001 > /dev/null 2>&1; then
                    echo "App is reachable at http://localhost:5001"
                    exit 0
                  fi

                  i=$((i+1))
                  echo "Waiting for app... attempt $i/$MAX"
                  sleep 2
                done

                echo "App did not respond after $MAX attempts"
                echo "===== Running containers ====="
                docker ps
                echo "===== App logs ====="
                docker logs notes_app_ci || true
                echo "===== Mongo logs ====="
                docker logs notes_mongo_ci || true
                exit 1
                '''
            }
        }

        stage('Run Selenium Tests in Docker') {
            steps {
                sh '''
                docker run --rm --network host \
                  -e APP_URL=http://localhost:5001 \
                  -v "$PWD/selenium-tests":/workspace \
                  -w /workspace \
                  markhobson/maven-chrome mvn test
                '''
            }
        }
    }

    post {
        always {
            catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                emailext(
                    subject: "${JOB_NAME} - Build #${BUILD_NUMBER} - ${currentBuild.currentResult}",
                    body: """
Build Result: ${currentBuild.currentResult}
Build URL: ${env.BUILD_URL}

Test results were generated by Jenkins pipeline.
""",
                    to: "${env.COMMIT_AUTHOR_EMAIL}"
                )
            }
        }
    }
}